# H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true